### ISSUE TITLE
Medway public toilet website

### ISSUE THREAD

**Issue by emily-dsl** [Sam-Rowe/justaddapicnic.com#31]
This has now been added to the Rochester Guildhall page and cliffe park page

**Comment by Sam-Rowe** [comment]
Why do we need a website of public toilets? or should we be looking to add special metadata for sites with a public toilet.

**Comment by emily-dsl** [comment]
For locations that do not have their own facilities it is important for visitors to know where the nearest public toilet is.  It also stops us getting into trouble with comments like McDonalds will let you use theirs.

**Comment by Sam-Rowe** [comment]
I agree, but how do we improve this presentation to our end users?

**Comment by Sam-Rowe** [comment]
How about we add meta: to the posts and use that to drive a set of icons to describe what is available at that site.

**Comment by emily-dsl** [comment]
New issue opened regarding the use of facilities icons.
